# Generate Data

* This notebook is created for simple data manipulation and conversion to keep the data ready for the RAG application.
* This notebook,
    1. Converts the xls data to CSV data for easier management.

## Import Libraries

In [1]:
import pandas as pd
from pathlib import Path

## Convert XLS To CSV

### Read XLS Files

In [2]:
data_path = Path("..","data","raw")
ratings_file_path = Path(data_path, "ratings.xlsx")
lines_file_path = Path(data_path, "lines.xlsx")

In [3]:
ratings = pd.read_excel(ratings_file_path, )
lines = pd.read_excel(lines_file_path)

In [4]:
ratings.head()

,Unnamed: 0,season,episode,episode_no(1-186),Title,AirDate,Rating,Num_Votes,Description,DirectedBy,WrittenBy,Director+Writer Combined,Total_lines,Total_scenes,year,month,day,Difference in days between air dates(season-wise)
0,0,1,1,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,"('Ken Kwapis', 'Ricky Gervais | Stephen Mercha...",229,39,2005,3,3,0
1,1,1,2,2,Diversity Day,2005-03-29,8.3,4213,Michael's off color remark puts a sensitivity ...,Ken Kwapis,B. J. Novak,"('Ken Kwapis', 'B. J. Novak')",217,35,2005,3,1,5
2,2,1,3,3,Health Care,2005-04-05,7.8,3536,Michael leaves Dwight in charge of picking the...,Ken Whittingham,Paul Lieberstein,"('Ken Whittingham', 'Paul Lieberstein')",244,39,2005,4,1,12
3,3,1,4,4,The Alliance,2005-04-12,8.1,3428,"Just for a laugh, Jim agrees to an alliance wi...",Bryan Gordon,Michael Schur,"('Bryan Gordon', 'Michael Schur')",265,49,2005,4,1,19
4,4,1,5,5,Basketball,2005-04-19,8.4,3745,Michael and his staff challenge the warehouse ...,Greg Daniels,Greg Daniels,"('Greg Daniels', 'Greg Daniels')",235,40,2005,4,1,26

In [5]:
## lets delete some unrequired columns
ratings.drop(columns=["Unnamed: 0", "Director+Writer Combined"], inplace=True)

In [6]:
ratings.head()

,season,episode,episode_no(1-186),Title,AirDate,Rating,Num_Votes,Description,DirectedBy,WrittenBy,Total_lines,Total_scenes,year,month,day,Difference in days between air dates(season-wise)
0,1,1,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0
1,1,2,2,Diversity Day,2005-03-29,8.3,4213,Michael's off color remark puts a sensitivity ...,Ken Kwapis,B. J. Novak,217,35,2005,3,1,5
2,1,3,3,Health Care,2005-04-05,7.8,3536,Michael leaves Dwight in charge of picking the...,Ken Whittingham,Paul Lieberstein,244,39,2005,4,1,12
3,1,4,4,The Alliance,2005-04-12,8.1,3428,"Just for a laugh, Jim agrees to an alliance wi...",Bryan Gordon,Michael Schur,265,49,2005,4,1,19
4,1,5,5,Basketball,2005-04-19,8.4,3745,Michael and his staff challenge the warehouse ...,Greg Daniels,Greg Daniels,235,40,2005,4,1,26

In [7]:
## print column names
pd.DataFrame(ratings.columns)

                                                    0
0                                              season
1                                             episode
2                                   episode_no(1-186)
3                                               Title
4                                             AirDate
5                                              Rating
6                                           Num_Votes
7                                         Description
8                                          DirectedBy
9                                           WrittenBy
10                                        Total_lines
11                                       Total_scenes
12                                               year
13                                              month
14                                                day
15  Difference in days between air dates(season-wise)

In [8]:
## lets rename the columns for consistancy.
ratings.rename(columns={
    "episode_no(1-186)": "episode_no",
    "Title":"title",
    "AirDate":"air_date",
    "Rating":"rating",
    "Num_Votes":"num_votes",
    "Description":"description",
    "DirectedBy":"directed_by",
    "WrittenBy": "written_by",
    "Total_lines":"total_lines",
    "Total_scenes":"total_scenes",
    "Difference in days between air dates(season-wise)":"air_dates_diff_days"
}, inplace=True)

In [9]:
ratings.head()

,season,episode,episode_no,title,air_date,rating,num_votes,description,directed_by,written_by,total_lines,total_scenes,year,month,day,air_dates_diff_days
0,1,1,1,Pilot,2005-03-24,7.5,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0
1,1,2,2,Diversity Day,2005-03-29,8.3,4213,Michael's off color remark puts a sensitivity ...,Ken Kwapis,B. J. Novak,217,35,2005,3,1,5
2,1,3,3,Health Care,2005-04-05,7.8,3536,Michael leaves Dwight in charge of picking the...,Ken Whittingham,Paul Lieberstein,244,39,2005,4,1,12
3,1,4,4,The Alliance,2005-04-12,8.1,3428,"Just for a laugh, Jim agrees to an alliance wi...",Bryan Gordon,Michael Schur,265,49,2005,4,1,19
4,1,5,5,Basketball,2005-04-19,8.4,3745,Michael and his staff challenge the warehouse ...,Greg Daniels,Greg Daniels,235,40,2005,4,1,26

In [10]:
ratings.shape

(186, 16)

In [11]:
lines.head()

,id,season,episode,scene,line_text,speaker,deleted
0,1,1,1,1,All right Jim. Your quarterlies look very good...,Michael,False
1,2,1,1,1,"Oh, I told you. I couldn't close it. So...",Jim,False
2,3,1,1,1,So you've come to the master for guidance? Is ...,Michael,False
3,4,1,1,1,"Actually, you called me in here, but yeah.",Jim,False
4,5,1,1,1,"All right. Well, let me show you how it's done.",Michael,False

In [12]:
lines.shape

(59909, 7)

In [13]:
pd.DataFrame(lines.columns)

           0
0         id
1     season
2    episode
3      scene
4  line_text
5    speaker
6    deleted

* I am not sure about the `id` column, but we are going to keep it as it is for now.

In [14]:
## Save to CSV
ratings.to_csv(Path(data_path,"ratings.csv"), index=False)
lines.to_csv(Path(data_path,"lines.csv"), index=False)

## Merging The Dataset
* We need to merge the dataset so that each row in lines have ratings, director etc info. 
* For this we need to merge based on Season and episode numbers

In [15]:
merged_data = lines.merge(
    ratings,
    on=["season", "episode"],  # Merge keys
    how="left"  # Keep all dialog lines, add matching episode metadata
)

In [16]:
merged_data.shape

(59909, 21)

In [17]:
merged_data.head()

,id,season,episode,scene,line_text,speaker,deleted,episode_no,title,air_date,...,num_votes,description,directed_by,written_by,total_lines,total_scenes,year,month,day,air_dates_diff_days
0,1,1,1,1,All right Jim. Your quarterlies look very good...,Michael,False,1,Pilot,2005-03-24,...,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0
1,2,1,1,1,"Oh, I told you. I couldn't close it. So...",Jim,False,1,Pilot,2005-03-24,...,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0
2,3,1,1,1,So you've come to the master for guidance? Is ...,Michael,False,1,Pilot,2005-03-24,...,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0
3,4,1,1,1,"Actually, you called me in here, but yeah.",Jim,False,1,Pilot,2005-03-24,...,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0
4,5,1,1,1,"All right. Well, let me show you how it's done.",Michael,False,1,Pilot,2005-03-24,...,4349,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0

* I think its safe to delete `episode_no` column since its redundant

In [18]:
merged_data.drop(columns=["episode_no"], inplace=True)

In [19]:
pd.DataFrame(merged_data.dtypes)

                                  0
id                            int64
season                        int64
episode                       int64
scene                         int64
line_text                    object
speaker                      object
deleted                        bool
title                        object
air_date             datetime64[ns]
rating                      float64
num_votes                     int64
description                  object
directed_by                  object
written_by                   object
total_lines                   int64
total_scenes                  int64
year                          int64
month                         int64
day                           int64
air_dates_diff_days           int64

In [20]:
merged_data.isna().sum()

id                     0
season                 0
episode                0
scene                  0
line_text              0
speaker                0
deleted                0
title                  0
air_date               0
rating                 0
num_votes              0
description            0
directed_by            0
written_by             0
total_lines            0
total_scenes           0
year                   0
month                  0
day                    0
air_dates_diff_days    0
dtype: int64

In [21]:
merged_data.isnull().sum()

id                     0
season                 0
episode                0
scene                  0
line_text              0
speaker                0
deleted                0
title                  0
air_date               0
rating                 0
num_votes              0
description            0
directed_by            0
written_by             0
total_lines            0
total_scenes           0
year                   0
month                  0
day                    0
air_dates_diff_days    0
dtype: int64

In [22]:
merged_data["line_text"] = merged_data["line_text"].astype(str)

In [23]:
merged_data["lines"] = merged_data["speaker"] + ": " + merged_data["line_text"]

In [24]:
merged_data.head()

,id,season,episode,scene,line_text,speaker,deleted,title,air_date,rating,...,description,directed_by,written_by,total_lines,total_scenes,year,month,day,air_dates_diff_days,lines
0,1,1,1,1,All right Jim. Your quarterlies look very good...,Michael,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,Michael: All right Jim. Your quarterlies look ...
1,2,1,1,1,"Oh, I told you. I couldn't close it. So...",Jim,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,"Jim: Oh, I told you. I couldn't close it. So..."
2,3,1,1,1,So you've come to the master for guidance? Is ...,Michael,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,Michael: So you've come to the master for guid...
3,4,1,1,1,"Actually, you called me in here, but yeah.",Jim,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,"Jim: Actually, you called me in here, but yeah."
4,5,1,1,1,"All right. Well, let me show you how it's done.",Michael,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,"Michael: All right. Well, let me show you how ..."

In [25]:
## save merge_data to csv
merged_data.to_csv(Path(data_path,"data.csv"), index=False)

## Creating MetaData for Agents

In [26]:
merged_data.head()

,id,season,episode,scene,line_text,speaker,deleted,title,air_date,rating,...,description,directed_by,written_by,total_lines,total_scenes,year,month,day,air_dates_diff_days,lines
0,1,1,1,1,All right Jim. Your quarterlies look very good...,Michael,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,Michael: All right Jim. Your quarterlies look ...
1,2,1,1,1,"Oh, I told you. I couldn't close it. So...",Jim,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,"Jim: Oh, I told you. I couldn't close it. So..."
2,3,1,1,1,So you've come to the master for guidance? Is ...,Michael,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,Michael: So you've come to the master for guid...
3,4,1,1,1,"Actually, you called me in here, but yeah.",Jim,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,"Jim: Actually, you called me in here, but yeah."
4,5,1,1,1,"All right. Well, let me show you how it's done.",Michael,False,Pilot,2005-03-24,7.5,...,The premiere episode introduces the boss and s...,Ken Kwapis,Ricky Gervais | Stephen Merchant | Greg Daniels,229,39,2005,3,3,0,"Michael: All right. Well, let me show you how ..."

In [27]:
unique_seasons = merged_data.season.unique()
unique_seasons

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

* To create season overview tool we need to extract following data for each season
    * Total episodes
    * List of unique actors in the season
    * List of unique directors in the season
    * List of unique writers in the season
* Similarly to create episode ratings we'll need to extract the following for each episode of each season
    * Ratings of the episode

In [65]:
# for season in unique_seasons:
#     characters = 
#     print(characters)

season = 1
merged_data.loc[merged_data["season"] == season,"air_date"].sort_values(ascending=True).unique()

<DatetimeArray>
['2005-03-24 00:00:00', '2005-03-29 00:00:00', '2005-04-05 00:00:00',
 '2005-04-12 00:00:00', '2005-04-19 00:00:00', '2005-04-26 00:00:00']
Length: 6, dtype: datetime64[ns]

In [100]:
from datetime import datetime
import json


metadata = []

for season in unique_seasons:
    total_episodes = merged_data.loc[merged_data["season"]
                                     == season, "episode"].unique().max()
    episodes_ratings = [float(merged_data.loc[(merged_data["season"] == season) & (
        merged_data["episode"] == episode), "rating"].unique()[0]) for episode in range(1, total_episodes+1)]
    episodes_dates = [str(air_date).split(" ")[0] for air_date in merged_data.loc[merged_data["season"] == season,"air_date"].sort_values(ascending=True).unique()]
    directors = [director.strip() for director in merged_data.loc[merged_data["season"]
                                == season, "directed_by"].unique()]
    season_writer = []
    for writers in merged_data.loc[merged_data["season"] == season,"written_by"].unique():
        writer_list = writers.split("|")
        season_writer = season_writer + writer_list
        writers = [writer.strip() for writer in season_writer]
        
    characters = merged_data.loc[merged_data["season"] == season,"speaker"].unique()
    
    metadata.append({
        "season":int(season),
        "total_episodes":int(total_episodes),
        "episodes_ratings":episodes_ratings,
        "episodes_dates":episodes_dates,
        "directors": list(directors),
        "writers":list(writers),
        "characters":list(characters)
    })
    
    
metadata[0]
    
with open(Path(data_path,"metadata.json"), "w") as fp:
    json.dump(metadata,fp)

In [104]:
merged_data["written_by"].value_counts()

written_by
Mindy Kaling                                       6648
Paul Lieberstein                                   4524
B. J. Novak                                        4396
Gene Stupnitsky | Lee Eisenberg                    4232
Brent Forrester                                    3225
Greg Daniels                                       3123
Jennifer Celotta                                   3020
Michael Schur                                      2587
Justin Spitzer                                     2514
Charlie Grandy                                     2038
Halsted Sullivan | Warren Lieberstein              2033
Daniel Chun                                        1925
Aaron Shure                                        1851
Robert Padnick                                     1185
Carrie Kemper                                      1183
Owen Ellickson                                     1107
Jennifer Celotta | Paul Lieberstein                 890
Allison Silverman                                   877
Steve Hely                                          860
Graham Wagner                                       823
Anthony Q. Farrell                                  754
Lester Lewis                                        717
Brent Forrester | Justin Spitzer                    706
Steve Carell                                        685
Niki Schwartz-Wright                                635
Amelie Gillette                                     603
Jon Vitti                                           568
Dan Greaney                                         567
Ryan Koh                                            563
Dan Sterling                                        556
Greg Daniels | Mindy Kaling                         552
Paul Lieberstein | Michael Schur                    544
Jonathan Green | Gabe Miller                        526
Lee Eisenberg | Gene Stupnitsky | Michael Schur     471
Larry Wilmore                                       401
Jennifer Celotta | Greg Daniels                     365
Tim McAuliffe                                       318
Peter Ocko                                          286
Jonathan Hughes                                     279
Ricky Gervais | Stephen Merchant | Greg Daniels     270
Ricky Gervais | Stephen Merchant                    191
Caroline Williams                                   180
Jason Kessler                                       131
Name: count, dtype: int64